version: '3.8'
services:
  php:
    build:
      context: ./php_setting
      dockerfile: php_Dockerfile
    volumes:
      - ./php_setting/backend:/var/www/html
  web:
    build:
      context: ./php_setting
      dockerfile: nginx_Dockerfile
    volumes:
      - ./php_setting/backend:/usr/share/nginx/html
    ports:
      - 2000:80
  database:
    build:
      context: ./mysql_setting
      dockerfile: Dockerfile